name: Simple Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y clang gcc make python3
    - name: make test
      run: make test
    - name: make example
      run: make example
    - name: Check dirty single-header
      run: git diff --exit-code ffc.h
